ID: com.sap.mta.test
version: 1.0.0

modules:
  - name: foo
    type: foo
    provides:
      - name: foo
    requires: [foo, bar]
    properties:
      dependency-type: hard

  - name: bar
    type: bar
    provides:
      - name: bar
